services:
  # YT Cipher
  yt-cipher:
    image: ghcr.io/kikkia/yt-cipher:master
    container_name: ejs_signature_api
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - lavalink_net

  # NodeLink
  nodelink:
    image: performanc/nodelink:latest
    container_name: nodelink_server
    restart: unless-stopped
    volumes:
      - ./config.js:/app/config.js
    depends_on:
      yt-cipher:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - lavalink_net

  # PostgreSQL DB
  postgres:
    image: postgres:16-alpine
    container_name: flayx_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flayx
      POSTGRES_USER: flayx
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-flayx_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flayx -d flayx"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - lavalink_net

  # FLAYX
  bot:
    image: ghcr.io/fllayy/flayx:latest
    container_name: flayx_bot
    restart: unless-stopped
    depends_on:
      nodelink:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - flayx.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - lavalink_net

networks:
  lavalink_net:
    driver: bridge

volumes:
  postgres_data:
